### ISSUE TITLE
GNE?

### ISSUE THREAD

**Issue by jhseo1107** [xnuk/xnuk#3]
GNE 원작자분 맞으십니까 아니십니까?
GNE 레포에서 여기 링크로 오는게 있더군요...

**Comment by xnuk** [comment]
원작자는 아닙니다. 현재 GNE 리포는 원작자가 개인적인 사정으로 리포를 내렸다가 다시 다른 분이 원작자의 허락을 맡고 재배포되는
것입니다. 저는 그 개인적인 사정을 존중해드리고 싶어서 원작자가 리포를 내린 시기에 제가 쓴 SSVM 구현체 역시 내린 것이었습니다.

해당 SSVM 구현체는 SSVM을 돌릴 수 있는 컴퓨터 자원인지 체크하고 돌릴 수 있으면 7시간을 기다리다 끝날 뿐인 그런 개그성
구현체였습니다. 저는 여전히 그 구현체가 80%의 유스케이스를 잡았다고 자부합니다

**Comment by jhseo1107** [comment]
아 그런거군요 답변 감사합니다
