### ISSUE TITLE
연락처 관련

### ISSUE THREAD

**Issue by kwon0408** [xnuk/xnuk#5]
![image](https://user-images.githubusercontent.com/31509569/58383889-b1ac3680-8016-11e9-8606-24d7960e1aa1.png)

https://twitter.com/x__nuk/status/1131580366819450882 에서 텔레그램 ID가 틀린 것 같아요

**Comment by xnuk** [comment]
감사합니다. 텔레그램 아이디를 정정했습니다. 맞는 아이디는 https://t.me/CuteEngineeringStudentsButt 입니다.

- https://twitter.com/x__nuk/status/1132841262761930752
